// Kanji data for N5 level with categories
const kanjiData = [
    { kanji: '一', correct: 'one', options: ['one', 'two', 'three', 'four'], category: 'numbers' },
    { kanji: '二', correct: 'two', options: ['one', 'two', 'five', 'six'], category: 'numbers' },
    { kanji: '三', correct: 'three', options: ['three', 'seven', 'eight', 'nine'], category: 'numbers' },
    { kanji: '四', correct: 'four', options: ['four', 'five', 'six', 'seven'], category: 'numbers' },
    { kanji: '五', correct: 'five', options: ['three', 'four', 'five', 'six'], category: 'numbers' },
    { kanji: '六', correct: 'six', options: ['four', 'five', 'six', 'seven'], category: 'numbers' },
    { kanji: '七', correct: 'seven', options: ['five', 'six', 'seven', 'eight'], category: 'numbers' },
    { kanji: '八', correct: 'eight', options: ['six', 'seven', 'eight', 'nine'], category: 'numbers' },
    { kanji: '九', correct: 'nine', options: ['seven', 'eight', 'nine', 'ten'], category: 'numbers' },
    { kanji: '十', correct: 'ten', options: ['eight', 'nine', 'ten', 'hundred'], category: 'numbers' },
    { kanji: '百', correct: 'hundred', options: ['ten', 'hundred', 'thousand', 'ten thousand'], category: 'numbers' },
    { kanji: '千', correct: 'thousand', options: ['hundred', 'thousand', 'ten thousand', 'million'], category: 'numbers' },
    { kanji: '万', correct: 'ten thousand', options: ['thousand', 'ten thousand', 'hundred thousand', 'million'], category: 'numbers' },
    { kanji: '円', correct: 'yen/circle', options: ['yen/circle', 'dollar', 'square', 'triangle'], category: 'numbers' },
    { kanji: '日', correct: 'day/sun', options: ['day/sun', 'moon', 'fire', 'water'], category: 'time' },
    { kanji: '月', correct: 'month/moon', options: ['day', 'month/moon', 'year', 'week'], category: 'time' },
    { kanji: '火', correct: 'fire', options: ['water', 'ice', 'fire', 'snow'], category: 'time' },
    { kanji: '水', correct: 'water', options: ['fire', 'water', 'wind', 'earth'], category: 'time' },
    { kanji: '木', correct: 'tree/wood', options: ['tree/wood', 'flower', 'grass', 'leaf'], category: 'time' },
    { kanji: '金', correct: 'gold/money', options: ['gold/money', 'silver', 'copper', 'iron'], category: 'time' },
    { kanji: '土', correct: 'soil/earth', options: ['soil/earth', 'water', 'fire', 'wind'], category: 'time' },
    { kanji: '年', correct: 'year', options: ['day', 'month', 'year', 'hour'], category: 'time' },
    { kanji: '時', correct: 'time/hour', options: ['time/hour', 'minute', 'second', 'day'], category: 'time' },
    { kanji: '分', correct: 'minute/part', options: ['hour', 'minute/part', 'second', 'day'], category: 'time' },
    { kanji: '半', correct: 'half', options: ['half', 'quarter', 'third', 'whole'], category: 'time' },
    { kanji: '今', correct: 'now', options: ['now', 'then', 'before', 'after'], category: 'time' },
    { kanji: '朝', correct: 'morning', options: ['morning', 'noon', 'evening', 'night'], category: 'time' },
    { kanji: '昼', correct: 'noon/daytime', options: ['morning', 'noon/daytime', 'evening', 'night'], category: 'time' },
    { kanji: '晩', correct: 'evening/night', options: ['morning', 'noon', 'evening/night', 'midnight'], category: 'time' },
    { kanji: '毎', correct: 'every', options: ['every', 'some', 'few', 'many'], category: 'time' },
    { kanji: '週', correct: 'week', options: ['day', 'week', 'month', 'year'], category: 'time' },
    { kanji: '人', correct: 'person', options: ['person', 'child', 'woman', 'man'], category: 'people' },
    { kanji: '男', correct: 'man', options: ['woman', 'man', 'child', 'boy'], category: 'people' },
    { kanji: '女', correct: 'woman', options: ['man', 'woman', 'girl', 'child'], category: 'people' },
    { kanji: '子', correct: 'child', options: ['child', 'adult', 'parent', 'teacher'], category: 'people' },
    { kanji: '学', correct: 'study/learning', options: ['study/learning', 'teaching', 'writing', 'reading'], category: 'education' },
    { kanji: '生', correct: 'life/birth', options: ['death', 'life/birth', 'sleep', 'wake'], category: 'people' },
    { kanji: '先', correct: 'previous/ahead', options: ['previous/ahead', 'next', 'behind', 'beside'], category: 'directions' },
    { kanji: '校', correct: 'school', options: ['school', 'home', 'office', 'store'], category: 'education' },
    { kanji: '友', correct: 'friend', options: ['friend', 'enemy', 'stranger', 'family'], category: 'people' },
    { kanji: '父', correct: 'father', options: ['mother', 'father', 'brother', 'sister'], category: 'family' },
    { kanji: '母', correct: 'mother', options: ['father', 'mother', 'brother', 'sister'], category: 'family' },
    { kanji: '兄', correct: 'older brother', options: ['older brother', 'younger brother', 'older sister', 'younger sister'], category: 'family' },
    { kanji: '姉', correct: 'older sister', options: ['older brother', 'younger brother', 'older sister', 'younger sister'], category: 'family' },
    { kanji: '弟', correct: 'younger brother', options: ['older brother', 'younger brother', 'older sister', 'younger sister'], category: 'family' },
    { kanji: '妹', correct: 'younger sister', options: ['older brother', 'younger brother', 'older sister', 'younger sister'], category: 'family' },
    { kanji: '大', correct: 'big', options: ['small', 'big', 'medium', 'tiny'], category: 'adjectives' },
    { kanji: '小', correct: 'small', options: ['big', 'large', 'small', 'huge'], category: 'adjectives' },
    { kanji: '高', correct: 'high/expensive', options: ['low', 'high/expensive', 'cheap', 'free'], category: 'adjectives' },
    { kanji: '安', correct: 'cheap/safe', options: ['expensive', 'dangerous', 'cheap/safe', 'risky'], category: 'adjectives' },
    { kanji: '新', correct: 'new', options: ['old', 'new', 'used', 'broken'], category: 'adjectives' },
    { kanji: '古', correct: 'old', options: ['new', 'old', 'modern', 'fresh'], category: 'adjectives' },
    { kanji: '多', correct: 'many', options: ['few', 'some', 'many', 'none'], category: 'adjectives' },
    { kanji: '少', correct: 'few/little', options: ['many', 'few/little', 'all', 'none'], category: 'adjectives' },
    { kanji: '長', correct: 'long/leader', options: ['short', 'long/leader', 'wide', 'narrow'], category: 'adjectives' },
    { kanji: '短', correct: 'short', options: ['long', 'short', 'tall', 'wide'], category: 'adjectives' },
    { kanji: '早', correct: 'early/fast', options: ['late', 'early/fast', 'slow', 'never'], category: 'adjectives' },
    { kanji: '暗', correct: 'dark', options: ['bright', 'dark', 'light', 'colorful'], category: 'adjectives' },
    { kanji: '明', correct: 'bright', options: ['dark', 'bright', 'dim', 'shadow'], category: 'adjectives' },
    { kanji: '元', correct: 'origin/health', options: ['origin/health', 'end', 'middle', 'side'], category: 'adjectives' },
    { kanji: '気', correct: 'spirit/feeling', options: ['body', 'spirit/feeling', 'mind', 'soul'], category: 'adjectives' },
    { kanji: '上', correct: 'up/above', options: ['down', 'up/above', 'left', 'right'], category: 'directions' },
    { kanji: '下', correct: 'down/below', options: ['up', 'down/below', 'inside', 'outside'], category: 'directions' },
    { kanji: '中', correct: 'middle/inside', options: ['outside', 'beside', 'middle/inside', 'around'], category: 'directions' },
    { kanji: '外', correct: 'outside', options: ['inside', 'outside', 'between', 'through'], category: 'directions' },
    { kanji: '内', correct: 'inside', options: ['outside', 'inside', 'beside', 'around'], category: 'directions' },
    { kanji: '左', correct: 'left', options: ['right', 'left', 'front', 'back'], category: 'directions' },
    { kanji: '右', correct: 'right', options: ['left', 'right', 'up', 'down'], category: 'directions' },
    { kanji: '前', correct: 'front/before', options: ['back', 'front/before', 'side', 'behind'], category: 'directions' },
    { kanji: '後', correct: 'behind/after', options: ['front', 'behind/after', 'beside', 'before'], category: 'directions' },
    { kanji: '北', correct: 'north', options: ['south', 'east', 'west', 'north'], category: 'directions' },
    { kanji: '南', correct: 'south', options: ['north', 'south', 'east', 'west'], category: 'directions' },
    { kanji: '東', correct: 'east', options: ['west', 'east', 'north', 'south'], category: 'directions' },
    { kanji: '西', correct: 'west', options: ['east', 'west', 'north', 'south'], category: 'directions' },
    { kanji: '出', correct: 'exit/go out', options: ['enter', 'exit/go out', 'stay', 'return'], category: 'verbs' },
    { kanji: '入', correct: 'enter', options: ['exit', 'enter', 'leave', 'pass'], category: 'verbs' },
    { kanji: '来', correct: 'come', options: ['go', 'come', 'leave', 'stay'], category: 'verbs' },
    { kanji: '行', correct: 'go', options: ['come', 'go', 'stay', 'return'], category: 'verbs' },
    { kanji: '帰', correct: 'return/go home', options: ['leave', 'arrive', 'return/go home', 'depart'], category: 'verbs' },
    { kanji: '立', correct: 'stand', options: ['sit', 'stand', 'lie', 'kneel'], category: 'verbs' },
    { kanji: '見', correct: 'see/look', options: ['hear', 'see/look', 'smell', 'taste'], category: 'verbs' },
    { kanji: '聞', correct: 'hear/ask', options: ['see', 'hear/ask', 'speak', 'write'], category: 'verbs' },
    { kanji: '読', correct: 'read', options: ['write', 'read', 'speak', 'listen'], category: 'verbs' },
    { kanji: '書', correct: 'write', options: ['read', 'write', 'speak', 'listen'], category: 'verbs' },
    { kanji: '話', correct: 'talk/speak', options: ['listen', 'write', 'talk/speak', 'read'], category: 'verbs' },
    { kanji: '言', correct: 'say/speech', options: ['hear', 'say/speech', 'write', 'read'], category: 'verbs' },
    { kanji: '食', correct: 'eat', options: ['drink', 'eat', 'sleep', 'walk'], category: 'verbs' },
    { kanji: '飲', correct: 'drink', options: ['eat', 'drink', 'cook', 'wash'], category: 'verbs' },
    { kanji: '買', correct: 'buy', options: ['sell', 'buy', 'trade', 'give'], category: 'verbs' },
    { kanji: '売', correct: 'sell', options: ['buy', 'sell', 'trade', 'rent'], category: 'verbs' },
    { kanji: '作', correct: 'make', options: ['break', 'make', 'fix', 'destroy'], category: 'verbs' },
    { kanji: '持', correct: 'hold/have', options: ['drop', 'hold/have', 'throw', 'catch'], category: 'verbs' },
    { kanji: '待', correct: 'wait', options: ['go', 'run', 'wait', 'hurry'], category: 'verbs' },
    { kanji: '休', correct: 'rest', options: ['work', 'rest', 'play', 'study'], category: 'verbs' },
    { kanji: '使', correct: 'use', options: ['throw', 'use', 'keep', 'hide'], category: 'verbs' },
    { kanji: '働', correct: 'work', options: ['rest', 'work', 'play', 'sleep'], category: 'verbs' },
    { kanji: '住', correct: 'live/reside', options: ['leave', 'live/reside', 'visit', 'travel'], category: 'verbs' },
    { kanji: '思', correct: 'think', options: ['forget', 'think', 'know', 'remember'], category: 'verbs' },
    { kanji: '知', correct: 'know', options: ['forget', 'think', 'know', 'learn'], category: 'verbs' },
    { kanji: '本', correct: 'book/origin', options: ['book/origin', 'paper', 'pen', 'desk'], category: 'nouns' },
    { kanji: '国', correct: 'country', options: ['city', 'country', 'village', 'town'], category: 'nouns' },
    { kanji: '語', correct: 'language', options: ['language', 'word', 'letter', 'sound'], category: 'nouns' },
    { kanji: '名', correct: 'name', options: ['name', 'age', 'place', 'thing'], category: 'nouns' },
    { kanji: '店', correct: 'shop/store', options: ['house', 'shop/store', 'office', 'school'], category: 'nouns' },
    { kanji: '駅', correct: 'station', options: ['station', 'airport', 'bus stop', 'port'], category: 'nouns' },
    { kanji: '車', correct: 'car/vehicle', options: ['car/vehicle', 'bicycle', 'train', 'bus'], category: 'nouns' },
    { kanji: '電', correct: 'electricity', options: ['water', 'electricity', 'gas', 'oil'], category: 'nouns' },
    { kanji: '雨', correct: 'rain', options: ['snow', 'rain', 'wind', 'cloud'], category: 'nature' },
    { kanji: '天', correct: 'heaven/sky', options: ['earth', 'heaven/sky', 'sea', 'mountain'], category: 'nature' },
    { kanji: '山', correct: 'mountain', options: ['valley', 'mountain', 'hill', 'plain'], category: 'nature' },
    { kanji: '川', correct: 'river', options: ['lake', 'river', 'sea', 'ocean'], category: 'nature' },
    { kanji: '海', correct: 'sea/ocean', options: ['river', 'lake', 'sea/ocean', 'pond'], category: 'nature' },
    { kanji: '花', correct: 'flower', options: ['tree', 'flower', 'grass', 'leaf'], category: 'nature' },
    { kanji: '犬', correct: 'dog', options: ['cat', 'dog', 'bird', 'fish'], category: 'animals' },
    { kanji: '猫', correct: 'cat', options: ['dog', 'cat', 'bird', 'rabbit'], category: 'animals' },
    { kanji: '魚', correct: 'fish', options: ['bird', 'fish', 'meat', 'vegetable'], category: 'animals' },
    { kanji: '肉', correct: 'meat', options: ['fish', 'meat', 'vegetable', 'fruit'], category: 'food' },
    { kanji: '色', correct: 'color', options: ['shape', 'color', 'size', 'weight'], category: 'other' },
    { kanji: '白', correct: 'white', options: ['black', 'white', 'red', 'blue'], category: 'colors' },
    { kanji: '黒', correct: 'black', options: ['white', 'black', 'red', 'green'], category: 'colors' },
    { kanji: '赤', correct: 'red', options: ['blue', 'red', 'green', 'yellow'], category: 'colors' },
    { kanji: '青', correct: 'blue', options: ['red', 'blue', 'green', 'yellow'], category: 'colors' }
];

// Category definitions with emoji and descriptions
const categories = {
    all: { name: 'All Categories', emoji: '🎌', description: 'Mix of all kanji' },
    numbers: { name: 'Numbers', emoji: '🔢', description: 'Number kanji (一、二、三...)' },
    time: { name: 'Time & Days', emoji: '⏰', description: 'Time, days, and dates' },
    family: { name: 'Family', emoji: '👨‍👩‍👧‍👦', description: 'Family members' },
    people: { name: 'People', emoji: '👥', description: 'People and society' },
    verbs: { name: 'Verbs', emoji: '🏃', description: 'Action words' },
    adjectives: { name: 'Adjectives', emoji: '✨', description: 'Descriptive words' },
    directions: { name: 'Directions', emoji: '🧭', description: 'Position and direction' },
    nature: { name: 'Nature', emoji: '🌳', description: 'Nature and weather' },
    colors: { name: 'Colors', emoji: '🎨', description: 'Color kanji' },
    animals: { name: 'Animals', emoji: '🐾', description: 'Animals and creatures' },
    nouns: { name: 'Common Nouns', emoji: '📦', description: 'Everyday objects' },
    education: { name: 'Education', emoji: '📚', description: 'School and learning' },
    food: { name: 'Food', emoji: '🍱', description: 'Food and meals' }
};